### ISSUE TITLE
🚀 [Feature] Frontend: Create own table with settings

### ISSUE THREAD

**Issue by Elweyn** [dreammall-earth/dreammall.earth#1007]
## 🚀 Feature
Who: users
What: Create own table, with chosen name and visibility / access rights
Why: I might want to give a hint about what my table is about. I might want to be found by anyone interested, or have a private talk with friends.

The name should be used in deep links as well (#1581 ).

### Design Templates
https://www.figma.com/design/nkCyyDFx7fGeBnguwpardz/Dreammall-pr%C3%A4si?node-id=3426-47324&t=hfsalBftC4qnbKwX-4
https://www.figma.com/design/nkCyyDFx7fGeBnguwpardz/Dreammall-pr%C3%A4si?node-id=3438-33901&t=hfsalBftC4qnbKwX-4

![Image](https://github.com/user-attachments/assets/fa254e59-121a-4c46-9128-e5c10e0a8154)
![Image](https://github.com/user-attachments/assets/0bf02d93-4853-4c39-8991-73d74f7be8b6)
![Image](https://github.com/user-attachments/assets/e7634616-17a2-4f29-8f6b-9d7ab9064181)
![Image](https://github.com/user-attachments/assets/c73a8444-84f3-4927-b26f-d18afc2de60e)
![Image](https://github.com/user-attachments/assets/58e88180-2526-499f-abe0-9e175094f7ab)

## Todos
- [ ] Let desktop button float at bottom of page
- [ ] Unify action list of desktop and mobile
- [ ] New action list to create own table (or open it, should it already exist)
- [ ] Implement dialog
- [ ] ...?

Backend
------

- [x] #1448
- [ ] Get list of users I can add to the table?

**Comment by sebastian2357** [comment]
### Grober Flow:

#### User klickt auf "Mall Talk"
  => request to Backend: joinMyRoom
     response: url zur BBB-Meeting
     
  => loading indicator "Dein Mall Talk wird vorbeitet"
  
  => IFrame with Meeting (Komponente: EmbeddedRoom)
  
  => Funktionalität des Buttons ändert sich zu:
     - Kontaktliste
     - Einzelne Kontakte können angefragt werden (erstmal nur als PING)
       - evtl. Schriftzug zu etwas wie 'benachrichtigen' ändern
     - Suche nach Usern möglich
          
####  Wenn Meeting bzw. Raum wieder geschlossen, muss sich die Funktion des Buttons wieder zurück verändern
    => Wie wird das erkannt? Backend -> Frontend?
    => wenn direkte Interaktion vom Front.
    => durch Fehler? Timeout?
    => Währung/Sessionkontigent aufgebraucht?
  
  
#### Raumname wird "irgendwie" über Cockpit geändert 
  
  
### Notizen:
 - Titel ändern zu "My Mall Talk"
  
  
  
### Offene Fragen:
 - werden alle User oder nur bestimmte User angezeigt?
    - nur User, die online sind?
    - braucht es eine Form von benachrichtigen?
