### ISSUE TITLE
🚀 [Feature] Frontend: My tables section

### ISSUE THREAD

**Issue by Elweyn** [dreammall-earth/dreammall.earth#1019]
## 🚀 Feature
Who: Users
What: I want to see ``my tables`` in the ``Cockpit``, and I want to be able to edit the definition of each tables.
Why: E.g. to remove tables that are no longer needed

![image](https://github.com/user-attachments/assets/8dbbb94f-4de1-4295-8a24-495f486a4418)

## 🤖 ToDo
- [ ] Clarify with @Hardy-Hart-am-Start how adding a table and editing looks like
- [ ] Is the backend ready for this @Mogge ?
- [ ] List of my tables
- [ ] Each item can be edited

**Comment by Bettelstab** [comment]
Hmmm I think I should work on this as part of #1788
