### ISSUE TITLE
🌟 [EPIC] Improve Presenter 

### ISSUE THREAD

**Issue by ulfgebhardt** [dreammall-earth/dreammall.earth#140]
## 🌟 EPIC

This EPIC describes various improvements for the presenter after it was initially released with #2 . Those tasks are result of incomplete or postponed tasks from before.

- [ ] Refactor presenter code (wished for by @maeckes-infinitylabs ). Limit ~6h - goals are to be defined, but the following suggestions are made:
  - [ ] Improve stories
  - [ ] Improve test coverage
  - [ ] Improve components & component reusability
- [ ] Sustainable fix for the safari menu - the menu will not adjust the more or less menu entries automatically on safari
- [ ] Double Opt-In for EMails
