### ISSUE TITLE
🌟 [EPIC] Download Newsletter

### ISSUE THREAD

**Issue by ulfgebhardt** [dreammall-earth/dreammall.earth#142]
## 🌟 EPIC

The design of Hardi included a Download Button to obtain the latest Newsletter.
The concept is to provide the user with an idea of what he can expect if he subscribes to the newsletter.

Initial investigation revealed that brevo is able to export newsletters as pdf.

- [ ] After sending the first newsletter we should show the Download Button again to obtain the corresponding PDF.
- [ ] We must provide a mechanic/description/option to update the target of the download button
- [ ] Describe what would be the next steps to improve this mechanism in the future/with more systems available
