### ISSUE TITLE
🌟 [EPIC] Logging

### ISSUE THREAD

**Issue by ulfgebhardt** [dreammall-earth/dreammall.earth#143]
## 🌟 EPIC

In order to properly monitor our services we should have a detailed logging, allowing us to identify problems and effectively debug our services.

This task would include:
- [ ] Develop Logging concept
- [ ] Implement logging, which could entail the following subtasks
  - [ ] Deployment
    - [ ] Build logging
    - [ ] Migration logging
    - [ ] Nginx logging
  - [ ] Backend
    - [ ] Apollo logging
    - [ ] Prisma logging
    - [ ] Event logging
  - [ ] Presenter
    - [ ] Access logging (most likely nginx logging)
- [ ] Investigate tools which can provide valuable insight in those log files & make that available if applicable
