### ISSUE TITLE
🌟 [EPIC] SSO Frontend

### ISSUE THREAD

**Issue by ulfgebhardt** [dreammall-earth/dreammall.earth#144]
## 🌟 EPIC

Wir werden mehrere Dienste miteinander verknüpfen müssen. Dies kann über einen Single-Sign-On-Dienst (SSO) erfolgen.

Wir haben bereits [Authentik](https://github.com/goauthentik/authentik) als die Software-Lösung identifiziert, für die wir uns entscheiden wollen.

- [x] Finde eine Strategie, um SSO für unsere Anwendung zu implementieren und wie Sie es richtig testen können.
- [x] Bereitstellung der Authentic Services innerhalb unserer Anwendungsorchestrierung

### Features
Alle Nutzer oder Besucher - unabhängig von Rolle und Rechten sollen sich auf DreamMall registrieren, einloggen und agieren können.
- [x] #288 - registrieren können, um sich einen Account anzulegen
- [x] #278 - einloggen können, um im eigenen Account im Rahmen meiner Rolle und Rechte agieren zu können
