### ISSUE TITLE
🌟 [EPIC] Admin

### ISSUE THREAD

**Issue by ulfgebhardt** [dreammall-earth/dreammall.earth#145]
## 🌟 EPIC

Wir benötigen eine Admin-Schnittstelle für den Zugriff auf Überwachungstools, die Konfiguration der Anwendungen und andere administrative Aufgaben.
Hierfür ist SSO erforderlich (siehe #144). Die Authentifizierung der Admin-Schnittstelle könnte der erste Test für die SSO-Dienste sein.

- [ ] Aufgaben für die Admin-Schnittstelle definieren
- [ ] Implementiere die Authentifizierung gegenüber der Administrationsschnittstelle und dem Backend und deren SSO-Ablauf
- [ ] Implementierung der Admin-Schnittstelle für die definierten Aufgaben

## 🤖 ToDo
- [ ] #842
- [x] #1010
- [ ] 🌟 [EPIC] Admin: Link to greenlight
- [ ] 🌟 [EPIC] Admin: Group overview
- [ ] 🌟 [EPIC] Admin: Project overview
- [ ] 🌟 [EPIC] Admin: Team overview

**Comment by ogerly** [comment]
![Präsentation_ogerly_2024-07-09T07_15_13 221Z](https://github.com/dreammall-earth/dreammall.earth/assets/1324583/ae64a22a-24d7-4107-bf9d-8436dab56bac)
