### ISSUE TITLE
🐛 [Bug] Can not join table of other people

### ISSUE THREAD

**Issue by Elweyn** [dreammall-earth/dreammall.earth#1550]
## 🐛 Bug
As a user on a macOS prior to _Sonoma_ with Safari browser (v < 17)
I can open the _open tables list_, but they are all greyed out and I can not join any open table.

## 🤖 Todo
- [x] collect information about OS and browser version
- [ ] reproduce the issue
- [ ] solve the issue
