### ISSUE TITLE
🌟 [EPIC] Presenter

### ISSUE THREAD

**Issue by Elweyn** [dreammall-earth/dreammall.earth#2]
## 🌟 EPIC

The project Dreammall.earth needs a presentation website that needs to be hosted. 
On the presentation website we need to gather emails for the marketing team.

## 🤖 ToDos
- [ ] 🚀 [Feature] Design: Create the design for the dreammall.earth website on Figma
- [ ] 🚀 [Feature] Frontend: Create the link between Figma and the Storybook with Chromatic
- [x] #3
- [x] #4

## Later
- [ ] 🚀 [Feature] Backend: Call a bank interface and set a user state
