### ISSUE TITLE
🌟 [EPIC] The next Refactor

### ISSUE THREAD

**Issue by ulfgebhardt** [dreammall-earth/dreammall.earth#210]
## 🌟 EPIC

Dieses EPIC beschreibt verschiedene Verbesserungen für die verschiedenen Teile der Software.
Es handelt sich um ein Sammelissue - Teile sind Überbleibsel aus https://github.com/dreammall-earth/dreammall.earth/issues/140 .

- [ ] **Fehler** welche es zu beheben gilt:
- [ ] **Refaktorierung** des Presentercodes:
- [ ] **Features** welche es nicht den ersten Release des Presenters geschafft haben:
  - [ ] https://github.com/dreammall-earth/dreammall.earth/issues/108
  - [ ] https://github.com/dreammall-earth/dreammall.earth/issues/184
- [ ] **Forschung**
  - [ ] https://github.com/dreammall-earth/dreammall.earth/issues/185
