### ISSUE TITLE
🌟 [EPIC] Onboarding

### ISSUE THREAD

**Issue by mahula** [dreammall-earth/dreammall.earth#2169]
## 🌟 Onboarding
Das Onboarding umfasst die Einstiegs- und Zugangsprozesse für die DreamMall Nutzer.
Für die Nutzer sollen sie selbsterklärend und einfach zugänglich sein.
Einladungen und E-Mails (z.B. _Signup_ und _Passwort zurücksetzen_) sollen die Nutzer eindeutig informieren und zu den möglichen Aktionen führen.
Damit die Nutzer problemlos aud die DreamMall kommen und auch weitere Nutzer einladen können.

Das Onboarding umfasst folgende Phasen und User Flows

### Phase 1
Dies ist die Einstiegsphase, in der neue Nutzer auf die DreamMall kommen können.
#### Signup - Registrierung
- [X] Einfacher Zugang zur Signup Page über den Presenter
- [ ] Einfacher, nachvollziehbarer Zugang zur Signup Page aus Einladung heraus
- [ ] Eindeutig informierende E-Mail mit - https://github.com/dreammall-earth/dreammall.earth/issues/2211
  - [x] dem entsprechenden Link zur Sigup Page
  - [ ] Hinweis, sich sein eigenes Profil im Cockpit zu pflegen
- [ ] Eindeutiger Flow, wenn sich mit registrierten Daten versucht wird zu registrieren

#### Signin - Login
- [X] Einfacher Zugang zur Signin Page über den Presenter

##### zur Registrierung
- [ ] Eindeutiger Link
  - a)  zu einer Landing Page mit Begrüßung, Erklärung und Link zur Registrierungsseite mit Hinweis bei Ungültigkeit
  - b) zur Signin Page
  - c) zum Presenter
- [ ] Eindeutiger Flow bei Verwendung eines bereits eingelösten Registrierungs-Links
##### an einen Tisch (ohne Registrierung)
- [x] Eindeutiger Link
- [x] Landing Page
  - [x]  mit Aufforderung zur Namenseingabe 
  - [ ] mit Hinweis auf Registrierungsmöglichkeit :question: 

### Phase 2
Diese Phase repräsentiert den Zugang zur DreamMall als bereits registrierte Nutzer.
#### Signin - Login
- [X] Einfacher Zugang zur Signin Page über den Presenter

#### Einladungen verschicken - #292
- [ ] Einfacher, selbsterklärender Flow, einen Einladungs-Link in der DreamMall zu generieren und zu kopieren
- [ ] Selbsterklärender einfacher Zugang zum Einladungs-Link in einem Tisch

#### Passwort zurücksetzen
- [x] Einfacher Zugang über die Signin Page
- [ ] Einfacher Zugang über die Signup Page :question:
- [ ] Eindeutig informierende E-Mail mit dem entsprechenden Link zur Recovery Page
    https://github.com/dreammall-earth/dreammall.earth/issues/2211

**Comment by ulfgebhardt** [comment]
Closing this as all issues seem to be addressed in other more specific issues - most notably https://github.com/dreammall-earth/dreammall.earth/issues/2211
