### ISSUE TITLE
[EPIC] User Authentication

### ISSUE THREAD

**Issue by mahula** [dreammall-earth/dreammall.earth#276]
## 🌟 EPIC
Alle Nutzer oder Besucher - unabhängig von Rolle und Rechten sollen sich auf DreamMallregistrieren, einloggen und agieren können.

### Features
- [ ] registrieren können, um sich einen Account anzulegen
- [ ] #278 - einloggen können, um im eigenen Account im Rahmen meiner Rolle und Rechte agieren zu können
- [ ] #144 - in allen zugänglichen Bereichen nach Login agieren können

**Comment by mahula** [comment]
Diese Features sind Teil des Epics #144
