### ISSUE TITLE
🚀 [Feature] Frontend: Use Stories from the Storybook to create the first page of the website

### ISSUE THREAD

**Issue by Elweyn** [dreammall-earth/dreammall.earth#3]
## 🚀 Feature
We have a link between Figma and Chromatic to create Stories in the Storybook.
Please use them to create the TopBar, the first page and the footer.

## 🤖 ToDo
- [ ] Use the TopBar Storie in the PageShell.vue
- [ ] Create the first page of the one pager
- [ ] Use the Footer Storie in the PageShell.vue

**Comment by ulfgebhardt** [comment]
This is split into several small issues assigned to and discussed with mackes
