### ISSUE TITLE
🌟 [EPIC] Authentik

### ISSUE THREAD

**Issue by Elweyn** [dreammall-earth/dreammall.earth#545]
### Feedback
- [X] #144 
- [ ] 🚀 [Feature] Darstellung des redirect soll den nutzer nich irritieren (Überarbeiten / Verbessern)
- [ ] 🚀 [Feature] Registrierungslink in EMail führt zu direkter Anmeldung
  Nuter soll nach verifizierung seiner Email in Frontend angemeldet sein
- [ ] #182 
- [ ] 🚀 [Feature] Authentik kann wechseln zwischen Registrieren und Anmeldung
- [ ] 🚀 [Feature] Authentik SignIn, SignUp, ... designen

### Weltencafé
- [ ] 🌟 [EPIC] SSO BigBlueButton
