### ISSUE TITLE
🚀 [Feature] Remove .vuepress from backend and presenter

### ISSUE THREAD

**Issue by Elweyn** [dreammall-earth/dreammall.earth#55]
## 🚀 Feature

In the backend and frontend boilerplate there is a .vuepress folder that don't have to be in the backend or presenter folder.
Open to discussion if we want it or not! 

## 🤖 ToDo

- [ ] Remove backend/.vuepress folder
- [ ] Remove backend docs GitHub pipeline
- [ ] Remove presenter/.vuepress folder
- [ ] Remove presenter docs GitHub pipeline
