### ISSUE TITLE
🚀 [Feature] Frontend: Header

### ISSUE THREAD

**Issue by Elweyn** [dreammall-earth/dreammall.earth#707]
## 🚀 Feature

In figma Hardy designed a Header for the Frontend, we need the component in our Frontend

## 🤖 ToDo 
- [ ] Create HeaderMenu Component from Figma
- [ ] Implement App Toggle
- [x] Make App Bar sticky at mobile
- [x] Implement floating second menu for mobile
- [x] Implement message icon with number of messages
- [x] Implement news icon with indicator
- [x] Implement search box?

## Open questions for designer
- [x] How does the open search box look like on mobile?
- [x] Where is search function on desktop?
- [x] How to find tables on mobile?
- [x] Light/dark switch on mobile?
