### ISSUE TITLE
🚀 [Feature] Frontend: Join Meeting Page

### ISSUE THREAD

**Issue by Elweyn** [dreammall-earth/dreammall.earth#724]
## 🚀 Feature

As a non registered user I want to join a meeting that was shared to me:
- Given I am on the frontend page ``joinMeeting``
- Then I enter my name and click on join meeting
- I get redirected to the BBB encoded link

As a non signed in user I want to join a meeting that was shared to me:
- Given I am on the frontend page ``joinMeeting``
- Then I click on sign in and enter my credentials
- I get redirected to the BBB encoded link

As a user I want to join open meetings, if I click on the meeting in the map:
- Given I am on the worldcafe
- Then I click on a meeting on the map
- I get redirected to the BBB encoded link

## Depends on
- [x] #1009

## 🤖 ToDo
- [ ] Create a component that redirect on a new tab to an encoded link
- [ ] Create a ``joinMeeting`` page to
  - [ ] Enter name and join meeting
  - [ ] Sign In
