### ISSUE TITLE
🚀 [Feature] Backend: Webhook to BBB

### ISSUE THREAD

**Issue by Elweyn** [dreammall-earth/dreammall.earth#726]
## 🚀 Feature
As User we want to see the open & closed tables (Meeting) and which user is in a table (join & leavesMeeting)

## 🤖 ToDos
- [ ] Setup hook openMeeting
- [ ] Setup hook closeMeeting
- [ ] Setup hook joinMeeting
- [ ] Setup hook leaveMeeting
