### ISSUE TITLE
💬 [Question] BBB: Are the Webhooks active

### ISSUE THREAD

**Issue by Elweyn** [dreammall-earth/dreammall.earth#728]
## 💬 Question
As backend developer I need to know the status of the BBB meetings.
This is better with webhooks instead of periodicaly pinging the BBB server.

## 🤖 ToDo
- [x] Check if Webhook are active
  - [ ] If yes: Close this issues
  - [x] If no: Create ``🚀 [Feature] Dev-Op: Activate Webhooks on BBB server`` issue
