### ISSUE TITLE
💥 [DevOps] Authentik: Change script to have sql dump

### ISSUE THREAD

**Issue by Elweyn** [dreammall-earth/dreammall.earth#888]
## 💥 DevOps

As reviewer I want to see the changes on the database in a file and not a a binary file.
- Application and provider export script
- Flow and stages export script
- System export script

## 🤖 ToDo
- [ ] Change binary dump to sql dump
  - [ ] Application and provider
  - [ ] Flow and stages
  - [ ] System export
- [ ] Add .env to add local, stage or live url
